#!/usr/bin/env bash
# Bootstrap the AE-TFPE framework on Google Colab (Linux + CUDA).
#
#   !bash scripts/colab_setup.sh
#
# Idempotent: safe to re-run after a runtime reset. Sets DATA_ROOT / OUTPUT_ROOT
# and friends, installs pinned dependencies, and verifies CUDA is visible.
#
# Nothing here is macOS-specific; do not add Homebrew or Finder assumptions.

set -euo pipefail

REPO_DIR="${REPO_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
DATA_ROOT="${DATA_ROOT:-/content/data/Plant_leaf_diseases_dataset}"
OUTPUT_ROOT="${OUTPUT_ROOT:-/content/output}"
CACHE_ROOT="${CACHE_ROOT:-/content/cache}"
MODEL_ROOT="${MODEL_ROOT:-/content/weights}"

echo "=== AE-TFPE Colab setup ==="
echo "repo        : ${REPO_DIR}"
echo "DATA_ROOT   : ${DATA_ROOT}"
echo "OUTPUT_ROOT : ${OUTPUT_ROOT}"

mkdir -p "${OUTPUT_ROOT}" "${CACHE_ROOT}" "${MODEL_ROOT}" "$(dirname "${DATA_ROOT}")"

echo
echo "--- dependencies ---"
pip install -q --upgrade pip
pip install -q -r "${REPO_DIR}/requirements.txt"

echo
echo "--- environment ---"
python - <<'PY'
import torch, sys
print(f"python      : {sys.version.split()[0]}")
print(f"torch       : {torch.__version__}")
print(f"cuda avail  : {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"gpu         : {torch.cuda.get_device_name(0)}")
    print(f"cuda version: {torch.version.cuda}")
    free, total = torch.cuda.mem_get_info()
    print(f"gpu memory  : {total/1e9:.1f} GB total, {free/1e9:.1f} GB free")
else:
    print("!! No CUDA device. Runtime > Change runtime type > GPU.")
PY

cat > "${REPO_DIR}/configs/local.yaml" <<EOF
# Generated by scripts/colab_setup.sh. Git-ignored.
env:
  DATA_ROOT: "${DATA_ROOT}"
  OUTPUT_ROOT: "${OUTPUT_ROOT}"
  CACHE_ROOT: "${CACHE_ROOT}"
  MODEL_ROOT: "${MODEL_ROOT}"
EOF

echo
echo "--- dataset ---"
if [ -d "${DATA_ROOT}/train" ]; then
  for split in train val test; do
    n=$(find "${DATA_ROOT}/${split}" -type f \( -iname '*.jpg' -o -iname '*.png' -o -iname '*.jpeg' \) 2>/dev/null | wc -l)
    c=$(find "${DATA_ROOT}/${split}" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l)
    echo "  ${split}: ${n} images, ${c} classes"
  done
else
  echo "  !! ${DATA_ROOT}/train not found."
  echo "     Mount Drive and unpack the dataset, e.g.:"
  echo "       from google.colab import drive; drive.mount('/content/drive')"
  echo "       !unzip -q /content/drive/MyDrive/<your>.zip -d /content/data"
fi

echo
echo "Setup complete. Next:"
echo "  python scripts/check_shapes.py"
echo "  python scripts/generate_corruptions.py"
echo "  python scripts/print_run_matrix.py"
