#!/usr/bin/env python
"""Ingest a completed training run and emit its evidence record.

Reads only what the run actually wrote. Any field the run did not record is
reported as ABSENT -- never inferred, never back-computed from a related
quantity, never filled from a different environment.

Refuses to touch test artifacts: `eval_summary.json`, `test_*.csv/json` and any
corruption evaluation are ignored even when present in the directory, so running
this on a run that later had test evaluation attached cannot leak test numbers
into a pre-adoption evidence review.

    python scripts/ingest_training_run.py \
        --run "$OUTPUT_ROOT/validation/C2_28_clean_sanity" \
        --out docs/C2_28_TRAINING_EVIDENCE.md

Pre-registered clean-sanity bands (fixed before the run, not revisable here):
    >= 0.95   LEARNABLE / PASS
    0.80-0.95 DEGRADED  / report without post-hoc tuning
    <  0.80   CATASTROPHIC / stop
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import statistics
import sys

PASS_BAND, DEGRADED_BAND = 0.95, 0.80

# Files that would carry test-set information. Never opened.
FORBIDDEN = ("eval_summary.json", "test_clean.csv", "test_clean.json",
             "test_corruptions.csv", "calibration_eval_summary.json")


def load_metrics(run: str) -> list[dict]:
    path = os.path.join(run, "metrics.csv")
    if not os.path.exists(path):
        return []
    with open(path) as fh:
        return list(csv.DictReader(fh))


def num(row: dict, key: str):
    v = row.get(key)
    if v is None or v == "":
        return None
    try:
        return float(v)
    except ValueError:
        return None


def fmt(v, spec=".4f", absent="—"):
    return absent if v is None else format(v, spec)


def trend(vals: list[float]) -> float:
    """Least-squares slope per epoch; 0.0 if fewer than two points."""
    n = len(vals)
    if n < 2:
        return 0.0
    xs = list(range(n))
    mx, my = statistics.fmean(xs), statistics.fmean(vals)
    den = sum((x - mx) ** 2 for x in xs)
    return 0.0 if den == 0 else sum((x - mx) * (y - my) for x, y in zip(xs, vals)) / den


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", required=True)
    ap.add_argument("--out", default=None)
    ap.add_argument("--title", default="C2-28 Clean-Sanity Training Evidence")
    ap.add_argument("--tail", type=int, default=10, help="epochs used for the late-trend fit")
    args = ap.parse_args()

    run = args.run
    if not os.path.isdir(run):
        print(f"ERROR: run directory not found: {run}", file=sys.stderr)
        print("Nothing is inferred when artifacts are missing. Provide the real "
              "directory, or state the evidence as unavailable.", file=sys.stderr)
        return 2

    present = sorted(os.listdir(run))
    rows = load_metrics(run)
    summary = {}
    sp = os.path.join(run, "train_summary.json")
    if os.path.exists(sp):
        summary = json.load(open(sp))

    env = summary.get("environment", {})
    proto = summary.get("protocol", {})
    model = summary.get("model", {})
    peak = summary.get("peak_memory", {})

    ckpt_path = os.path.join(run, "checkpoint.pt")
    ckpt_mb = round(os.path.getsize(ckpt_path) / (1024 ** 2), 2) if os.path.exists(ckpt_path) else None
    ckpt_meta = {}
    if ckpt_path and os.path.exists(ckpt_path):
        try:
            import torch
            c = torch.load(ckpt_path, map_location="cpu", weights_only=False)
            ckpt_meta = {"epoch": c.get("epoch"), "val_top1": c.get("val_top1"),
                         "n_classes": len(c.get("classes", []) or []),
                         "n_tensors": len(c.get("model", {}) or {}),
                         "n_values": sum(v.numel() for v in (c.get("model") or {}).values())}
            del c
        except Exception as exc:  # noqa: BLE001
            ckpt_meta = {"error": str(exc)}

    L = []
    A = L.append
    A(f"# {args.title}\n")
    A(f"**Run directory:** `{run}`  ")
    A(f"**Generated by:** `scripts/ingest_training_run.py` — reads only recorded fields; "
      f"absent fields are marked ABSENT, never inferred.\n")

    A("## 0. Provenance\n")
    A("| Field | Value |")
    A("|---|---|")
    A(f"| Arm / name | {summary.get('name', 'ABSENT')} |")
    A(f"| Config | {summary.get('config', 'ABSENT')} |")
    A(f"| Commit | `{env.get('git_commit', 'ABSENT')}` |")
    A(f"| Repo dirty | {env.get('git_dirty', 'ABSENT')} |")
    A(f"| Device | {summary.get('device', 'ABSENT')} |")
    A(f"| GPU | {env.get('gpu', env.get('cuda_device', 'ABSENT'))} |")
    A(f"| torch | {env.get('torch', 'ABSENT')} |")
    A(f"| CUDA available | {env.get('cuda_available', 'ABSENT')} |")
    A(f"| Platform | {env.get('platform', 'ABSENT')} |")
    A(f"| Epochs (protocol) | {proto.get('epochs', 'ABSENT')} |")
    A(f"| Batch size | {proto.get('batch_size', 'ABSENT')} |")
    A(f"| Seed / deterministic | {proto.get('seed', 'ABSENT')} / {proto.get('deterministic', 'ABSENT')} |")
    A(f"| Optimiser / lr | {proto.get('optimizer', 'ABSENT')} / {proto.get('lr', 'ABSENT')} |")
    A(f"| AMP | {proto.get('amp', 'ABSENT')} |")
    A(f"| Checkpoint selection | {proto.get('checkpoint_selection', 'ABSENT')} |")
    A(f"| Files present | {', '.join(present)} |")
    skipped = [f for f in present if f in FORBIDDEN]
    if skipped:
        A(f"| **Deliberately not read** | {', '.join(skipped)} (test-set artifacts) |")
    A("")

    if not rows:
        A("## 1. Per-epoch table\n")
        A("**ABSENT — `metrics.csv` not found. No epoch-level analysis is possible.**\n")
        out = args.out or os.path.join(run, "EVIDENCE.md")
        open(out, "w").write("\n".join(L) + "\n")
        print("\n".join(L))
        print(f"\nwrote {out}", file=sys.stderr)
        return 1

    cols = set(rows[0])
    has = {k: (k in cols) for k in
           ("train_top5", "val_top5", "train_ae_recon", "train_ae_kl",
            "peak_cuda_alloc_mb", "stage")}

    A("## 1. Per-epoch record — every column the run actually wrote\n")
    A("| ep | phase | train loss | train top-1 | train top-5 | val top-1 | val top-5 "
      "| AE recon | AE KL | lr | sec | peak CUDA MiB |")
    A("|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for r in rows:
        A(f"| {r.get('epoch','')} | {r.get('stage','—')} | {fmt(num(r,'train_loss'))} "
          f"| {fmt(num(r,'train_top1'))} | {fmt(num(r,'train_top5'))} "
          f"| {fmt(num(r,'val_top1'))} | {fmt(num(r,'val_top5'))} "
          f"| {fmt(num(r,'train_ae_recon'),'.5f')} | {fmt(num(r,'train_ae_kl'),'.5f')} "
          f"| {fmt(num(r,'lr'),'.6f')} | {fmt(num(r,'seconds'),'.1f')} "
          f"| {fmt(num(r,'peak_cuda_alloc_mb'),'.1f')} |")
    A("")
    missing = [k for k, v in has.items() if not v]
    if missing:
        A(f"**Columns ABSENT from this run:** {', '.join(missing)}. Not inferred.\n")

    # ---------------- best / final / convergence ----------------
    joint = [r for r in rows if r.get("stage") != "ae_warmup"] or rows
    v1 = [(int(r["epoch"]), num(r, "val_top1")) for r in joint if num(r, "val_top1") is not None]
    v5 = [(int(r["epoch"]), num(r, "val_top5")) for r in joint if num(r, "val_top5") is not None]

    best1 = max(v1, key=lambda t: t[1]) if v1 else None
    best5 = max(v5, key=lambda t: t[1]) if v5 else None
    final1 = v1[-1] if v1 else None
    final5 = v5[-1] if v5 else None

    A("## 2. Best / final / convergence\n")
    A("| Quantity | Value |")
    A("|---|---|")
    A(f"| Best validation top-1 | {fmt(best1[1] if best1 else None)} at epoch {best1[0] if best1 else '—'} |")
    A(f"| Best validation top-5 | {fmt(best5[1] if best5 else None)} at epoch {best5[0] if best5 else '—'} |")
    A(f"| Final validation top-1 | {fmt(final1[1] if final1 else None)} (epoch {final1[0] if final1 else '—'}) |")
    A(f"| Final validation top-5 | {fmt(final5[1] if final5 else None)} (epoch {final5[0] if final5 else '—'}) |")
    A(f"| `best_val_top1` in summary | {fmt(summary.get('best_val_top1'))} |")
    if ckpt_meta:
        A(f"| Checkpoint epoch / val top-1 | {ckpt_meta.get('epoch','—')} / {fmt(ckpt_meta.get('val_top1'))} |")
    A("")

    verdict_traj = "ABSENT"
    if v1 and len(v1) >= 3:
        tail = [y for _, y in v1[-args.tail:]]
        slope = trend(tail)
        gap_to_best = best1[1] - final1[1]
        late_best = best1[0] >= v1[-1][0] - max(2, len(v1) // 10)
        A(f"**Late-phase trend** (last {len(tail)} joint epochs): slope "
          f"**{slope:+.5f} val-top-1 per epoch**; best-to-final gap {gap_to_best:+.4f}; "
          f"best epoch {'is' if late_best else 'is not'} in the final stretch.\n")
        if slope > 0.0015 and late_best:
            verdict_traj = ("STILL IMPROVING — the run had not converged at the epoch budget. "
                            "A longer schedule is a legitimate follow-up, but is NOT a "
                            "post-hoc tune of this result.")
        elif abs(slope) <= 0.0015:
            verdict_traj = "PLATEAUED — additional epochs at this schedule are unlikely to help."
        elif slope < -0.0015:
            verdict_traj = "DEGRADING LATE — check for over-fitting or schedule mismatch."
        else:
            verdict_traj = "MIXED — see the per-epoch table."
        A(f"**Trajectory:** {verdict_traj}\n")

    # ---------------- pre-registered verdict ----------------
    A("## 3. Pre-registered clean-sanity verdict\n")
    A("Bands fixed before the run and not revisable: ≥ 0.95 PASS · 0.80–0.95 DEGRADED "
      "(report, do not tune) · < 0.80 CATASTROPHIC.\n")
    if best1:
        b = best1[1]
        band = ("PASS — LEARNABLE" if b >= PASS_BAND else
                "DEGRADED — report without post-hoc tuning" if b >= DEGRADED_BAND else
                "CATASTROPHIC — stop and report")
        A(f"Best clean validation top-1 = **{b:.4f}** → **{band}**\n")
        if b < PASS_BAND:
            A(f"Trajectory qualifier: {verdict_traj}\n")
    else:
        A("**ABSENT — no validation top-1 recorded; no verdict can be issued.**\n")

    # ---------------- efficiency ----------------
    A("## 4. Training efficiency — this run only\n")
    secs = [num(r, "seconds") for r in rows if num(r, "seconds") is not None]
    warm = [num(r, "seconds") for r in rows
            if r.get("stage") == "ae_warmup" and num(r, "seconds") is not None]
    jnt = [num(r, "seconds") for r in rows
           if r.get("stage") == "joint" and num(r, "seconds") is not None]
    A("| Quantity | Value |")
    A("|---|---|")
    A(f"| Mean epoch wall-clock | {fmt(statistics.fmean(secs),'.1f') if secs else 'ABSENT'} s |")
    A(f"| Mean AE-warm-up epoch | {fmt(statistics.fmean(warm),'.1f') if warm else 'ABSENT'} s |")
    A(f"| Mean joint-training epoch | {fmt(statistics.fmean(jnt),'.1f') if jnt else 'ABSENT'} s |")
    A(f"| Total training wall-clock | {fmt(summary.get('train_seconds'),'.1f')} s "
      f"({fmt((summary.get('train_seconds') or 0)/3600,'.2f')} h) |")
    A(f"| Peak CUDA allocated | {peak.get('peak_allocated_mb', 'ABSENT')} MiB |")
    A(f"| Peak CUDA reserved | {peak.get('peak_reserved_mb', 'ABSENT')} MiB |")
    if not peak.get("available", False):
        A(f"| Peak-memory note | {peak.get('note', 'ABSENT')} |")
    A(f"| Checkpoint size | {ckpt_mb if ckpt_mb is not None else 'ABSENT'} MB |")
    A(f"| Checkpoint tensors / values | {ckpt_meta.get('n_tensors','ABSENT')} / "
      f"{ckpt_meta.get('n_values','ABSENT'):,}" if isinstance(ckpt_meta.get('n_values'), int)
      else f"| Checkpoint tensors / values | ABSENT |")
    A("")
    A("Trainable / frozen / total parameter split is **not written by `train.py`**; "
      "take it from the architecture benchmark, which measures it directly.\n")

    # ---------------- AE behaviour ----------------
    A("## 5. Auto-encoder behaviour — clean training only\n")
    rec = [(int(r["epoch"]), num(r, "train_ae_recon")) for r in rows
           if num(r, "train_ae_recon") is not None]
    if not rec:
        A("**ABSENT — no `train_ae_recon` column. No AE conclusion can be drawn.**\n")
    else:
        first, last = rec[0][1], rec[-1][1]
        lo = min(rec, key=lambda t: t[1])
        A(f"- Reconstruction loss: **{first:.5f} → {last:.5f}** "
          f"({'decreased' if last < first else 'did NOT decrease'}), "
          f"minimum {lo[1]:.5f} at epoch {lo[0]}.")
        rs = trend([y for _, y in rec])
        A(f"- Trend: **{rs:+.6f} per epoch** "
          f"({'falling' if rs < 0 else 'flat or rising'}).")
        if v1:
            joint_rec = [(e, y) for e, y in rec if e >= (rec[0][0] + len(warm))]
            A(f"- Classification improved alongside reconstruction: "
              f"val top-1 {v1[0][1]:.4f} → {v1[-1][1]:.4f}.")
        A("")
        A("**Pre-registered attribution:** a flat or rising reconstruction loss implicates "
          "the decoder; a falling reconstruction loss with stagnant accuracy implicates "
          "the grid/interface.\n")
        A("**Valid conclusion from clean training only:** whether the feature-space AE is "
          "trainable and does not prevent learning the clean classification task. "
          "**No noise-resilience conclusion may be drawn from this run** — no corrupted "
          "data was evaluated.\n")

    A("## 6. What this run does NOT establish\n")
    A("- No robustness or noise-resilience claim — clean data only.")
    A("- No superiority over any baseline — no fair Protocol-B baseline was trained here.")
    A("- No component attribution — PE, transformer and AE were not ablated.")
    A("- No test-set performance — the test split was never constructed "
      "(`scripts/verify_no_test_access.py`).")
    A("")

    out = args.out or os.path.join(run, "EVIDENCE.md")
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    open(out, "w").write("\n".join(L) + "\n")
    print("\n".join(L))
    print(f"\nwrote {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
